---
title: "gganimate"
date: "17 December 2018"
output: html_document
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
 
```{r}
library(ggplot2)
library(gganimate)
library(transformr)
library(magick)
 
p <- 
  ggplot2::ggplot(airquality, aes(Day, Temp)) +
  ggplot2::geom_line(size = 2, colour = 'steelblue') +
  gganimate::transition_states(Month, 4, 1) +
  gganimate::shadow_mark(size = 1, colour = 'grey')
 
# When knitting you may get this error: Error in gzfile(file, "wb") : cannot open the connection
# If you do, put the RStudio project in a folder that has a short file path such as your desktop as advised here
# https://stackoverflow.com/questions/15363076/error-in-gzfilefile-wb-cannot-open-the-connection-or-compressed-file
# You also need to install this https://github.com/thomasp85/transformr as described here...https://github.com/thomasp85/gganimate/issues/190
animate(p, renderer = magick_renderer())
```

Adapting this example: https://mitchelloharawild.com/wombat-gganimate/#37

```{r}
p <- 
  ggplot2::ggplot(economics) +
  ggplot2::aes(date, unemploy) +
  ggplot2::geom_line() +
  gganimate::transition_reveal(date)

gganimate::animate(p, renderer = magick_renderer())
```

This example: https://mitchelloharawild.com/wombat-gganimate/#42

```{r}
library(datasauRus)

p <- 
  ggplot2::ggplot(datasaurus_dozen) +
  ggplot2::aes(x, y) +
  geom_point() +
  gganimate::transition_states(dataset, 3, 1) +
  ggplot2::labs(title = "Dataset: {closest_state}")

gganimate::animate(p, renderer = magick_renderer())
```

This example: https://mitchelloharawild.com/wombat-gganimate/#74

```{r}
library(gapminder)
theme_set(theme_bw())

p <- 
  ggplot2::ggplot(gapminder) + 
  ggplot2::aes(x = gdpPercap, y=lifeExp, size = pop, colour = country) +
  ggplot2::geom_point(show.legend = FALSE) +
  ggplot2::scale_x_log10() +
  ggplot2::scale_color_viridis_d() +
  ggplot2::scale_size(range = c(2, 12)) +
  ggplot2::labs(x = "GDP per capita", y = "Life expectancy") +
  gganimate::transition_time(year) +
  ggplot2::labs(title = "Year: {frame_time}") +
  gganimate::shadow_wake(wake_length = 0.1, alpha = FALSE)

gganimate::animate(p, renderer = magick_renderer())
```


```{r}
p <- 
  ggplot2::ggplot(iris, aes(Petal.Length, Sepal.Length)) +
  ggplot2::geom_point(size = 2) +
  ggplot2::labs(title = "{closest_state}") +
  gganimate::transition_states(Species, transition_length = 4, state_length = 1) +
  gganimate::shadow_wake(wake_length = 0.1)

gganimate::animate(p, renderer = magick_renderer())
```
```{r}
p <- 
  ggplot2::ggplot(airquality, aes(Day, Temp)) +
  ggplot2::geom_line(color = 'red', size = 1) +
  gganimate::transition_time(Month) +
  gganimate::shadow_mark(colour = 'black', size = 0.75)

gganimate::animate(p, renderer = magick_renderer())
```

